### ISSUE TITLE
Lỗi UI chọn coding ra trắc nghiệm

### ISSUE THREAD

**Issue by minhkhangit123** [1753003/DATN_He-Thong-Danh-gia-ky-nang-Lap-trinh-SV#176]
![image](https://user-images.githubusercontent.com/36289576/129482649-9baad957-efdf-427c-9a21-64c22aaca90f.png)
![image](https://user-images.githubusercontent.com/36289576/129482656-2c00bf38-a49b-4d51-8451-aed3008c8f50.png)

**Comment by Fr3aKiNg** [comment]
I have this issue too, pls fix ASAP!

**Comment by 1753003** [comment]
oh I would ask pon fix that soon
tks guys
